apiVersion: v1
kind: Service
metadata:
  name: learner-report-cs-be-service
spec:
  selector:
    app: learner-report-cs-be
  ports:
    - protocol: TCP
      port: {{ .Values.backend.servicePort }}
      targetPort: 3001
  type: ClusterIP
